"use client";

import { useState, useCallback } from "react";
import type { Scorecard, DimensionScore, FieldAudit } from "@/lib/types";

interface ScoreResultsProps {
  scorecard: Scorecard;
  onReset: () => void;
}

const DIMENSION_KEYS: (keyof Scorecard["dimensions"])[] = [
  "contentCompleteness",
  "variantHandling",
  "sellerIntegrity",
  "eligibilityFlags",
  "contentQuality",
  "enrichment",
];

const DIMENSION_LABELS: Record<keyof Scorecard["dimensions"], string> = {
  contentCompleteness: "Content Completeness",
  variantHandling: "Variant Handling",
  sellerIntegrity: "Seller & Policy Integrity",
  eligibilityFlags: "Eligibility Flags",
  contentQuality: "Content Quality",
  enrichment: "Enrichment",
};

const DIMENSION_DESCRIPTIONS: Record<keyof Scorecard["dimensions"], string> = {
  contentCompleteness: "Required product fields like title, image, price",
  variantHandling: "Variant structure, per-variant pricing & stock",
  sellerIntegrity: "Return policy, seller info, target countries",
  eligibilityFlags: "Search & checkout eligibility signals",
  contentQuality: "Description depth, structured data, GTIN",
  enrichment: "Reviews, Q&A, video, demographics, materials",
};

function gradeColor(grade: DimensionScore["grade"]): string {
  switch (grade) {
    case "A":
      return "text-emerald-700";
    case "B":
      return "text-text";
    case "C":
      return "text-amber-700";
    case "D":
      return "text-orange-700";
    case "F":
      return "text-accent";
    default:
      return "text-text";
  }
}

function gradeBg(grade: DimensionScore["grade"]): string {
  switch (grade) {
    case "A":
      return "bg-emerald-700/10";
    case "B":
      return "bg-text/5";
    case "C":
      return "bg-amber-700/10";
    case "D":
      return "bg-orange-700/10";
    case "F":
      return "bg-accent/10";
    default:
      return "bg-text/5";
  }
}

function scoreBarColor(score: number): string {
  if (score >= 80) return "bg-emerald-700";
  if (score >= 60) return "bg-text-secondary";
  if (score >= 40) return "bg-amber-700";
  return "bg-accent";
}

function statusIcon(status: FieldAudit["status"]): string {
  switch (status) {
    case "present":
      return "\u2713";
    case "warn":
      return "\u26A0";
    case "partial":
      return "\u25D0";
    case "missing":
      return "\u2717";
    default:
      return "?";
  }
}

function statusColor(status: FieldAudit["status"]): string {
  switch (status) {
    case "present":
      return "text-emerald-700";
    case "warn":
      return "text-amber-700";
    case "partial":
      return "text-amber-700";
    case "missing":
      return "text-accent";
    default:
      return "text-text";
  }
}

function formatDate(iso: string): string {
  try {
    const d = new Date(iso);
    return d.toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return iso;
  }
}

// ---------------------------------------------------------------------------
// Build plain-text report for clipboard / email
// ---------------------------------------------------------------------------

function buildReportText(sc: Scorecard): string {
  const lines: string[] = [];
  lines.push(`CARVE — Agent Readiness Report`);
  lines.push(`${"═".repeat(50)}`);
  lines.push(``);
  lines.push(`URL: ${sc.url}`);
  lines.push(`Score: ${sc.overallScore}/100 (${sc.overallGrade})`);
  lines.push(`Analyzed: ${formatDate(sc.analyzedAt)}`);
  lines.push(``);
  lines.push(sc.headline);
  lines.push(``);
  lines.push(sc.summary);
  lines.push(``);
  lines.push(`${"─".repeat(50)}`);
  lines.push(`SCORECARD`);
  lines.push(`${"─".repeat(50)}`);

  for (const key of DIMENSION_KEYS) {
    const dim = sc.dimensions[key];
    lines.push(``);
    lines.push(`${DIMENSION_LABELS[key]}: ${dim.score}/100 (${dim.grade})`);
    for (const f of dim.findings) {
      lines.push(`  • ${f}`);
    }
    for (const r of dim.recommendations) {
      lines.push(`  → ${r}`);
    }
  }

  lines.push(``);
  lines.push(`${"─".repeat(50)}`);
  lines.push(`${sc.sampleSize} products sampled • ${sc.discoveredFeeds.length} data sources found`);
  lines.push(``);
  lines.push(`Generated by Carve — https://carve.co`);

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Field Breakdown sub-component
// ---------------------------------------------------------------------------

function FieldBreakdown({ fields }: { fields: FieldAudit[] }) {
  if (!fields || fields.length === 0) return null;

  const missingFields = fields.filter(
    (f) => f.status === "missing" || f.status === "partial" || f.status === "warn"
  );

  return (
    <div className="mt-4 mx-4 mb-4">
      <div className="border border-border/40 rounded-sm overflow-hidden">
        <table className="w-full">
          <thead>
            <tr className="bg-text/[0.03]">
              <th className="py-2 px-3 text-left font-sans text-[10px] uppercase tracking-wider text-text-tertiary">
                Status
              </th>
              <th className="py-2 px-3 text-left font-sans text-[10px] uppercase tracking-wider text-text-tertiary">
                ACP Field
              </th>
              <th className="py-2 px-3 text-left font-sans text-[10px] uppercase tracking-wider text-text-tertiary hidden sm:table-cell">
                Tier
              </th>
              <th className="py-2 px-3 text-right font-sans text-[10px] uppercase tracking-wider text-text-tertiary">
                Coverage
              </th>
            </tr>
          </thead>
          <tbody>
            {fields.map((field) => (
              <tr
                key={field.fieldName}
                className="border-t border-border/30 hover:bg-text/[0.02] transition-colors"
              >
                <td className="py-1.5 px-3">
                  <span className={`font-mono text-sm ${statusColor(field.status)}`}>
                    {statusIcon(field.status)}
                  </span>
                </td>
                <td className="py-1.5 px-3">
                  <span className="font-mono text-xs text-text">
                    {field.fieldName}
                  </span>
                  {field.qualityNote && (
                    <span className="font-mono text-[10px] text-text-tertiary ml-1.5">
                      — {field.qualityNote}
                    </span>
                  )}
                </td>
                <td className="py-1.5 px-3 hidden sm:table-cell">
                  <span
                    className={`font-mono text-[10px] uppercase tracking-wide ${
                      field.tier === "required"
                        ? "text-accent"
                        : field.tier === "conditional"
                          ? "text-amber-700"
                          : "text-text-tertiary"
                    }`}
                  >
                    {field.tier}
                  </span>
                </td>
                <td className="py-1.5 px-3 text-right">
                  <div className="inline-flex items-center gap-2">
                    <div className="w-12 h-1 bg-border/30 hidden sm:block">
                      <div
                        className={`h-1 ${
                          field.coverage === 100
                            ? "bg-emerald-700"
                            : field.coverage > 0
                              ? "bg-amber-700"
                              : "bg-border/50"
                        }`}
                        style={{ width: `${field.coverage}%` }}
                      />
                    </div>
                    <span className="font-mono text-xs text-text-secondary w-8 text-right">
                      {field.coverage}%
                    </span>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {missingFields.length > 0 && (
        <div className="mt-3 space-y-1.5 px-1">
          {missingFields
            .filter((f) => f.fixHint)
            .slice(0, 5)
            .map((f) => (
              <div
                key={f.fieldName}
                className="font-mono text-xs text-accent leading-snug flex gap-1.5"
              >
                <span className="flex-shrink-0">&rarr;</span>
                <span>
                  <span className="text-text-secondary">{f.fieldName}:</span> {f.fixHint}
                </span>
              </div>
            ))}
          {missingFields.filter((f) => f.fixHint).length > 5 && (
            <p className="font-mono text-[10px] text-text-tertiary italic">
              +{missingFields.filter((f) => f.fixHint).length - 5} more recommendations
            </p>
          )}
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Share Toolbar
// ---------------------------------------------------------------------------

function ShareToolbar({ scorecard }: { scorecard: Scorecard }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    const text = buildReportText(scorecard);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = text;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  }, [scorecard]);

  const handleEmail = useCallback(() => {
    const subject = encodeURIComponent(
      `Agent Readiness Report: ${scorecard.url} — ${scorecard.overallScore}/100`
    );
    const body = encodeURIComponent(buildReportText(scorecard));
    window.open(`mailto:?subject=${subject}&body=${body}`, "_self");
  }, [scorecard]);

  return (
    <div className="flex items-center gap-3">
      <button
        onClick={handleCopy}
        className="btn-secondary text-xs py-1.5 px-3 inline-flex items-center gap-2"
      >
        {copied ? (
          <>
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
            </svg>
            Copied
          </>
        ) : (
          <>
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
            Copy Report
          </>
        )}
      </button>

      <button
        onClick={handleEmail}
        className="btn-secondary text-xs py-1.5 px-3 inline-flex items-center gap-2"
      >
        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
        </svg>
        Email Report
      </button>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Dimension Row — a single row in the wide list
// ---------------------------------------------------------------------------

function DimensionRow({
  dimKey,
  dim,
  isExpanded,
  onToggle,
}: {
  dimKey: keyof Scorecard["dimensions"];
  dim: DimensionScore;
  isExpanded: boolean;
  onToggle: () => void;
}) {
  const hasFields = dim.fields && dim.fields.length > 0;

  return (
    <div className="border-b border-border/50 last:border-0">
      <button
        onClick={onToggle}
        className="w-full text-left group transition-colors hover:bg-text/[0.02]"
        disabled={!hasFields}
      >
        <div className="flex items-center gap-4 px-4 py-4 sm:px-5">
          <div
            className={`flex-shrink-0 w-10 h-10 flex items-center justify-center font-display text-lg font-bold rounded-sm ${gradeColor(dim.grade)} ${gradeBg(dim.grade)}`}
          >
            {dim.grade}
          </div>

          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2">
              <span className="font-sans text-sm font-medium text-text truncate">
                {DIMENSION_LABELS[dimKey]}
              </span>
            </div>
            <p className="font-mono text-[11px] text-text-tertiary mt-0.5 truncate hidden sm:block">
              {DIMENSION_DESCRIPTIONS[dimKey]}
            </p>
          </div>

          <div className="flex items-center gap-3 flex-shrink-0">
            <div className="w-20 sm:w-32 h-1.5 bg-border/30 rounded-sm hidden sm:block">
              <div
                className={`h-1.5 rounded-sm transition-all duration-700 ${scoreBarColor(dim.score)}`}
                style={{ width: `${dim.score}%` }}
              />
            </div>
            <span className="font-mono text-sm font-medium text-text w-8 text-right">
              {dim.score}
            </span>
          </div>

          {hasFields && (
            <div className="flex-shrink-0 w-5 text-text-tertiary group-hover:text-text transition-colors">
              <svg
                className={`w-4 h-4 transition-transform duration-200 ${isExpanded ? "rotate-180" : ""}`}
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth={2}
              >
                <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
              </svg>
            </div>
          )}
        </div>

        {(dim.findings.length > 0 || dim.recommendations.length > 0) && (
          <div className="px-4 sm:px-5 pb-3 pl-[4.25rem] sm:pl-[4.75rem] space-y-1">
            {dim.findings.map((f, i) => (
              <p key={`f-${i}`} className="font-mono text-xs text-text-secondary leading-snug">
                <span className="text-text-tertiary mr-1">&bull;</span>{f}
              </p>
            ))}
            {dim.recommendations.map((r, i) => (
              <p key={`r-${i}`} className="font-mono text-xs text-accent leading-snug">
                <span className="mr-1">&rarr;</span>{r}
              </p>
            ))}
          </div>
        )}
      </button>

      {isExpanded && hasFields && (
        <FieldBreakdown fields={dim.fields} />
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export default function ScoreResults({
  scorecard,
  onReset,
}: ScoreResultsProps) {
  const [expandedDimensions, setExpandedDimensions] = useState<Set<string>>(
    new Set()
  );

  function toggleDimension(key: string) {
    setExpandedDimensions((prev) => {
      const next = new Set(prev);
      if (next.has(key)) {
        next.delete(key);
      } else {
        next.add(key);
      }
      return next;
    });
  }

  return (
    <div className="max-w-4xl mx-auto">
      {/* ===== Section 1: Headline & Overall Score ===== */}
      <div>
        <div className="border-t-2 border-text" />

        <h2
          className="font-display font-medium text-text mt-6 mb-4 leading-tight"
          style={{ fontSize: "clamp(1.5rem, 4vw, 2.2rem)" }}
        >
          {scorecard.headline}
        </h2>

        <div className="flex flex-col sm:flex-row gap-6 items-start mb-6">
          <div className="flex items-baseline gap-2 flex-shrink-0">
            <span className="font-display text-6xl font-bold text-text leading-none">
              {scorecard.overallScore}
            </span>
            <span className="font-display text-4xl font-bold text-accent leading-none">
              {scorecard.overallGrade}
            </span>
          </div>

          <p className="font-sans italic text-text-secondary text-sm leading-relaxed">
            {scorecard.summary}
          </p>
        </div>

        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-4">
          <ShareToolbar scorecard={scorecard} />
          <p className="font-mono text-[10px] text-text-tertiary italic">
            Deterministic scores &bull; AI commentary only
          </p>
        </div>

        <div className="border-t border-border" />
      </div>

      {/* ===== Section 2: Dimensions — Wide List ===== */}
      <div className="mt-8">
        <div className="flex items-baseline justify-between mb-4">
          <h3 className="font-display font-medium text-xl md:text-2xl text-text">
            Scorecard
          </h3>
          <span className="font-mono text-xs text-text-tertiary">
            {scorecard.sampleSize} products sampled
          </span>
        </div>

        <div className="border border-border rounded-sm">
          <div className="flex items-center gap-4 px-4 sm:px-5 py-2.5 bg-text/[0.03] border-b border-border/50">
            <div className="w-10 flex-shrink-0">
              <span className="font-sans text-[10px] uppercase tracking-wider text-text-tertiary">
                Grade
              </span>
            </div>
            <div className="flex-1">
              <span className="font-sans text-[10px] uppercase tracking-wider text-text-tertiary">
                Dimension
              </span>
            </div>
            <div className="flex items-center gap-3 flex-shrink-0">
              <span className="font-sans text-[10px] uppercase tracking-wider text-text-tertiary hidden sm:block w-32 text-right">
                Progress
              </span>
              <span className="font-sans text-[10px] uppercase tracking-wider text-text-tertiary w-8 text-right">
                Score
              </span>
              <div className="w-5" />
            </div>
          </div>

          {DIMENSION_KEYS.map((key) => {
            const dim = scorecard.dimensions[key];
            return (
              <DimensionRow
                key={key}
                dimKey={key}
                dim={dim}
                isExpanded={expandedDimensions.has(key)}
                onToggle={() => toggleDimension(key)}
              />
            );
          })}
        </div>
      </div>

      {/* ===== Section 3: Discovered Feeds ===== */}
      <div className="mt-8">
        <div className="border-t border-border pt-6">
          <h4 className="font-sans text-xs uppercase tracking-wider text-text-tertiary mb-3">
            Discovered Data Sources
          </h4>

          {scorecard.discoveredFeeds.length > 0 ? (
            <ul className="space-y-2">
              {scorecard.discoveredFeeds.map((feed, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-emerald-700 font-mono text-sm flex-shrink-0">
                    &#10003;
                  </span>
                  <div className="min-w-0">
                    <span className="font-mono text-xs text-text font-medium uppercase">
                      {feed.type}
                    </span>
                    <span className="font-mono text-xs text-text-secondary ml-2 break-all">
                      {feed.url}
                    </span>
                    {feed.productCount !== null && (
                      <span className="font-mono text-xs text-text-tertiary ml-2">
                        ({feed.productCount} products)
                      </span>
                    )}
                  </div>
                </li>
              ))}
            </ul>
          ) : (
            <p className="font-mono text-xs text-text-tertiary italic">
              No structured product feeds were discovered. This site may rely on
              client-side rendering or non-standard data formats.
            </p>
          )}
        </div>
      </div>

      {/* ===== Section 4: Store Metadata ===== */}
      {scorecard.storeMeta && (
        <div className="mt-8">
          <div className="border-t border-border pt-6">
            <h4 className="font-sans text-xs uppercase tracking-wider text-text-tertiary mb-3">
              Store Metadata
            </h4>
            <div className="grid grid-cols-2 gap-x-6 gap-y-2">
              {scorecard.storeMeta.sellerName && (
                <>
                  <span className="font-mono text-xs text-text-secondary">Seller</span>
                  <span className="font-mono text-xs text-text">{scorecard.storeMeta.sellerName}</span>
                </>
              )}
              {scorecard.storeMeta.platform && (
                <>
                  <span className="font-mono text-xs text-text-secondary">Platform</span>
                  <span className="font-mono text-xs text-text capitalize">{scorecard.storeMeta.platform}</span>
                </>
              )}
              {scorecard.storeMeta.storeCountry && (
                <>
                  <span className="font-mono text-xs text-text-secondary">Country</span>
                  <span className="font-mono text-xs text-text">{scorecard.storeMeta.storeCountry}</span>
                </>
              )}
              {scorecard.storeMeta.targetCountries.length > 0 && (
                <>
                  <span className="font-mono text-xs text-text-secondary">Target Markets</span>
                  <span className="font-mono text-xs text-text">{scorecard.storeMeta.targetCountries.join(", ")}</span>
                </>
              )}
              <span className="font-mono text-xs text-text-secondary">Return Policy</span>
              <span className="font-mono text-xs text-text">
                {scorecard.storeMeta.returnPolicy ? "\u2713 Found" : "\u2717 Not found"}
              </span>
              <span className="font-mono text-xs text-text-secondary">Privacy Policy</span>
              <span className="font-mono text-xs text-text">
                {scorecard.storeMeta.privacyPolicyUrl ? "\u2713 Found" : "\u2717 Not found"}
              </span>
              <span className="font-mono text-xs text-text-secondary">Terms of Service</span>
              <span className="font-mono text-xs text-text">
                {scorecard.storeMeta.termsOfServiceUrl ? "\u2713 Found" : "\u2717 Not found"}
              </span>
            </div>
          </div>
        </div>
      )}

      {/* ===== Section 5: CTA ===== */}
      <div className="mt-8">
        <div className="card-elevated text-center">
          <h4 className="font-display font-medium text-xl md:text-2xl text-text mb-2">
            Want to improve your score?
          </h4>
          <p className="font-display italic text-text-secondary text-base mb-6">
            Carve can help you go from {scorecard.overallGrade} to A.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4">
            <a href="mailto:william@usecarve.com" className="btn-accent">
              Book a Call
            </a>
            <button onClick={onReset} className="btn-secondary">
              Score Another Site
            </button>
          </div>
        </div>

        <p className="font-mono text-xs text-text-tertiary text-center mt-4">
          Analyzed {formatDate(scorecard.analyzedAt)}
        </p>
      </div>
    </div>
  );
}
